// Generated by Selenium IDE
const { Builder, By } = require("selenium-webdriver");

describe("inventory", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("inventory", async function () {
    await driver.get("https://app2.jubelio.com/login");
    await driver.manage().window().setRect({ width: 697, height: 539 });

    // Masukkan email
    await driver.findElement(By.name("email")).sendKeys("enjiimarnii@gmail.com");
    await driver.sleep(1000); // Jeda 1 detik

    // Masukkan password
    await driver.findElement(By.name("password")).sendKeys("Enjimarni1@");
    await driver.sleep(1000); // Jeda 1 detik

    // Klik tombol login
    await driver.findElement(By.css(".ladda-label")).click();
    await driver.sleep(3000); // Jeda 3 detik untuk menunggu proses login

    // Navigasi ke halaman inventory
    await driver.get("https://app2.jubelio.com/home/inventory/");
    await driver.manage().window().setRect({ width: 697, height: 539 });
    await driver.sleep(2000); // Jeda 2 detik

    // Klik checkbox
    await driver.findElement(By.css("span .react-grid-checkbox-label")).click();
    await driver.sleep(1000); // Jeda 1 detik

    // Arahkan mouse ke tombol tertentu
    const element = await driver.findElement(By.css(".ladda-button:nth-child(3)"));
    await driver.actions({ bridge: true }).moveToElement(element).perform();
    await driver.sleep(1000); // Jeda 1 detik

    // Klik tombol submit
    await driver.findElement(By.css(".btn-primary > .ladda-label")).click();
    await driver.sleep(2000); // Jeda 2 detik

    // Isi tanggal
    await driver.findElement(By.css(".form-group:nth-child(2) .form-control")).sendKeys("29 Des 2024");
    await driver.sleep(1000); // Jeda 1 detik
  });
});
